FROM arm32v7/elixir:1.8-slim

RUN apt-get update && \
    apt-get install -y masscan

# Compile vaporator dependences
WORKDIR /vaporator
COPY . .

ENV MIX_ENV=prod

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix deps.compile
